### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by LupoA**
1. Address #51 
2. Address #50 
3. Address #18 by adding new algorithmical parameter "plateau_id". It is defaulted to the value that was previously hardcoded.
4. Removed a bunch of classes that are no longer needed (HLT class and GPerrorHLT class, their job is done by InverseProblemWrapper). Related examples are also removed.

### CODE REVIEW

**Comment by LupoA** [comment]
Also going for #28

**Comment by LupoA** [comment]
Also #32

**Comment by LupoA** [comment]
GP_class is disabled for the time being. I should restore it in the next weeks

**Comment by LupoA** [comment]
Does it work for you to have this merged or would it interfere with the release?
@nickforce989 @edbennett

**Comment by nickforce989** [comment]
@LupoA , at a first glance: It doesn't look like so. Moreover my data release is based on the version that I have uploaded on 'pip', which is the one that is currently on main (before your PR). Unless you don't plan to push it to pip surely it's fine. Otherwise, if you want to push the updated version to pip, I might want to do all the checks to make sure.

**Comment by edbennett** [comment]
Since Niccolò is pinning against a version from Pip, then even if there are breaking changes, provided you also update the version number, then it will not cause issues. (Definitely don't push a new version without updating the version number, as otherwise it gets very confusing when two different installations of the "same version" have different functionality.)

**Comment by nickforce989** [comment]
Ed is right, I was about amending my message saying the same thing.

**Pull request merged**
